apiVersion: v1
kind: Service
metadata:
  name: sample-service-{{ .Values.color }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: sample-deployment
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
